ejp-rd-vp/vp-dp-frontend

components/DiscoverySourcesTable.vue
pages/discovery/sources.vue

*  If the logo is not available show the resource title
* Check #18 
* close #18

#18 - Handle resourceLogo is not available

---

layouts/default.vue

* Prevent saving the notifications cookies twice
* check #20 
* close #20

#20 - Cookies are saved twice

---

components/search/DiscoverySearchResults.vue

* New loading spinner
* check #24 
* close #24

#24 - Show loading spinner during resource loading

---

components/search/DiscoverySearch.vue

* Make search bar label italic
* check #32 
* close #32

#32 - Design improvements

---

pages/imprint.vue

* Add missing information in imprint page
* check #35 
* close #35

#35 - Update imprint page

---

components/DisclaimerNotice.vue

* Update disclaimer notice
* check #38 
* close #38

#38 - Update disclaimer notice

---

components/search/DiscoverySearchResults.vue

* Stop fetching non-queryable resources
* check #43 
* close #43

#43 - Update vp network resources

---

components/DiscoverySourcesTable.vue
components/dialogs/ResourceInfoDialog.vue

* Delete resource email address
* check #46 
* close #46

#46 - Update resource contact info

---

components/dialogs/AcceptFunctionalCookiesDialog.vue

*  Display used cookies upon clicking
* check #48 
* close #48

#48 - VP portal available only with cookie acceptance

---

components/dialogs/AcceptFunctionalCookiesDialog.vue
layouts/default.vue
nuxt.config.js
plugins/vuex-persist.js
store/user_configs.js

* Save CookiesAccepted to the local storage using vuex-persist
* check #53 
* close #53

#53 - CookiesAccepted should be saved in local storage

---

components/dialogs/AcceptFunctionalCookiesDialog.vue
nuxt.config.js

* Remove the v-row wrapper from accept cookies dialog
* check #55 
* close #55

#55 - Update accept cookies dialog

---

pages/index.vue

* Add brackets
* check #57 
* close #57

#57 - Update intro text

---

layouts/error.vue
nuxt.config.js

* Redirect to vp-portal after logout
* check #70 
* close #70

#70 - Redirect to vp-portal after logout

---

components/DiscoverySourcesTable.vue
components/search/DiscoverySearchResults.vue
components/search/DiscoverySearchWithAutoComplete.vue
components/search/SearchAutoComplete.vue
components/search/SearchFilters.vue
components/search/SuggestedCodes.vue
nuxt.config.js
pages/discovery/index.vue

* Adjust all components to the New Backend.
* check #82 
* close #82

#82 - Adjust to the New Backend

---

assets/md/about.md

* Update of the about page content
* close https://github.com/ejp-rd-vp/vp-dp-frontend/issues/74

74 update about page content

---

components/DiscoverySourcesTable.vue
components/search/SearchFilters.vue

- Adjust-resourcetypes
* Add icons of the resource type
* Check the icons on the VP NETWORK RESOURCE page.

#88-Adjust-resourcetypes

---

components/DiscoverySourcesTable.vue

* change description
* start application and check if the descriptions are changed

#93 - Resource Type Description and Icons

---

components/search/DiscoverySearchWithAutoComplete.vue
components/search/SearchFilters.vue
pages/discovery/index.vue

* selected resourceTypes in filter were not included in the query, which is fixed in this pr
* create a query with selecting different resourceType filters and check whther they are considered

#98 - Filters are ignored

---

pages/discovery/index.vue

- update mapping endpoint (updated in the backend)
- change if-clause that method for retrieving orphacodes to the respective genes are requested
* search for genes like 'SPAST' and check whether expected results are returned

#109 - Fix gene search

---

assets/md/releasenote.md
layouts/default.vue
pages/releasenote.vue

* page with release note was added
* check release note page and content

#108 add release note

---

components/DiscoverySourcesTable.vue
components/Flashcards.vue

* Remove the Flashcards delimiters and change the position of the icons in the page discovery source table.
* The Flashcards Delimiters should be invisible and the icons of the Resources should be after the VPContentDiscovery Button.

101 improvements of the dev instanz

---

components/DiscoverySourcesTable.vue

* Display of the connected icons in green when the resource is connected and in red when the resource is not connected.
* Go to VP Network Resources
* Connected icons should be green and not connected should be red.

91 display the connected icon in green or red on the frontend

---

components/search/DiscoverySearchResults.vue

- add alert with error message

#123 - Error handling for negotiator

---

components/search/SuggestedCodes.vue
pages/discovery/index.vue

* Change in the design of the related diseases
* Make a search
* The content of related diseases should be more explicit and understandable to the user

121 redisign releated deseases

---

layouts/default.vue

-Ensure that all menu items are displayed on small screens.
* All the menu items are displayed on small screens
* Change the screen size to use the menu for small screens.
* Check that all menu items are present.

#135-menu-elements-for-small-screens

---

components/search/DiscoverySearchResults.vue
layouts/default.vue
nuxt.config.js
pages/login/index.vue

* Adjusting the method fetchnegotiator
* Adjusting the small menu items
* Perform a search (example: 730)
* Expand the BBMRI resource catalogue
* Click on the Negotiator button
* You should be redirected to the Negotiator page.

139 send token to negotiator
